[package]

name = "easter"
version = "0.0.4"
authors = ["Dave Herman <dherman@mozilla.com>"]
license = "MIT"
description = "Type definitions for ECMAScript abstract syntax trees."
repository = "https://github.com/dherman/esprit"

[dependencies]
joker = { version = "0.0.4", path = "../joker" }
